version: "3.8"

services:
  web:
    build: . # Caminho para o Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes: # Sincroniza os arquivos locais com o container
      - .:/code
    ports: 
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: # Daqui pra baixo faz com que o banco de dados persista a cada execução
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: